<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserProfile extends Model
{
    use HasFactory;

    protected $fillable = [
        'school_id',
        'user_id',
        'role',
        'phone',
        'address',
        'avatar_url',
        'two_factor_enabled',
        'two_factor_secret',
        'two_factor_confirmed_at',
        'two_factor_recovery_codes',
        'two_factor_enforced_at',
    ];

    /**
     * The TOTP secret and the recovery codes are second authentication factors:
     * anyone holding them can mint valid codes. Encrypted at rest so that a
     * database dump — the thing 2FA is meant to survive — does not hand them
     * over. They were previously stored as plaintext.
     */
    protected $casts = [
        'two_factor_enabled' => 'boolean',
        'two_factor_secret' => 'encrypted',
        'two_factor_recovery_codes' => 'encrypted:array',
        'two_factor_confirmed_at' => 'datetime',
        'two_factor_enforced_at' => 'datetime',
    ];

    /**
     * Never serialise the second factor into an API response. `hidden` is a
     * backstop — no controller should be returning this model raw anyway.
     */
    protected $hidden = [
        'two_factor_secret',
        'two_factor_recovery_codes',
    ];

    /**
     * Enrolment is only complete once a code generated by the admin's own
     * authenticator has been verified. `two_factor_enabled` alone is not
     * enough: it can be true while the secret was issued and never scanned.
     */
    public function hasCompletedTwoFactor(): bool
    {
        return $this->two_factor_enabled
            && $this->two_factor_confirmed_at !== null
            && trim((string) $this->two_factor_secret) !== '';
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function school()
    {
        return $this->belongsTo(School::class);
    }
}
