<?php

namespace Tests\Feature;

use App\Models\CbtExam;
use App\Models\CbtExamQuestion;
use App\Models\CbtQuestionGroup;
use App\Models\QuestionBankItem;
use App\Models\School;
use App\Models\SchoolClass;
use App\Models\Subject;
use App\Models\User;
use App\Models\UserProfile;
use App\Services\CbtExamService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

/**
 * The determinism contract — docs/offline-cbt-client.md §10.
 *
 * `seededShuffle` is a Fisher–Yates driven by a seeded MINSTD LCG, chosen so
 * paper order is stable forever across PHP versions. The offline client will
 * reimplement it, and the day the two implementations disagree is the day a
 * resumed or re-synced candidate silently gets a different paper than they
 * sat — with nothing in any log to say so.
 *
 * `tests/fixtures/cbt-shuffle-parity.json` is the contract between them. It
 * was generated by a standalone reference implementation written from the
 * specification rather than by `CbtExamService`, so agreement here means the
 * rules are reproducible from the spec. Whoever writes the desktop client
 * asserts the same file from the other side; whoever changes the ordering
 * rules will find this test in their way, which is the point.
 *
 * **Do not regenerate this fixture to make a failing test pass.** A red test
 * here means either the server drifted or the vectors are wrong, and the
 * difference matters.
 */
class CbtShuffleParityTest extends TestCase
{
    use RefreshDatabase;

    private array $fixture;
    private School $school;
    private Subject $subject;
    private SchoolClass $class;
    private User $teacher;

    protected function setUp(): void
    {
        parent::setUp();

        $path = base_path('tests/fixtures/cbt-shuffle-parity.json');
        $this->assertFileExists($path, 'The shuffle parity vectors are missing.');
        $this->fixture = json_decode(file_get_contents($path), true);

        $this->school = School::create([
            'name' => 'Graceland College', 'slug' => 'graceland', 'subdomain' => 'graceland',
        ]);
        $this->class = SchoolClass::create(['school_id' => $this->school->id, 'name' => 'JSS 2']);
        $this->subject = Subject::create(['school_id' => $this->school->id, 'name' => 'English', 'code' => 'ENG']);

        $this->teacher = User::create([
            'name' => 'Mrs Adeyemi', 'email' => 'adeyemi@graceland.test', 'password' => bcrypt('password'),
        ]);
        UserProfile::create(['school_id' => $this->school->id, 'user_id' => $this->teacher->id, 'role' => 'teacher']);
    }

    /** The primitive itself, across seed edge cases and realistic paper sizes. */
    public function test_seeded_shuffle_matches_the_committed_vectors(): void
    {
        $service = app(CbtExamService::class);

        foreach ($this->fixture['seeded_shuffle'] as $vector) {
            $actual = $service->seededShuffle(collect($vector['input']), $vector['seed'])->all();

            $this->assertSame(
                $vector['output'],
                $actual,
                sprintf('Shuffle drifted for seed %d, length %d.', $vector['seed'], $vector['length'])
            );
        }
    }

    /**
     * Option order is seeded per question (`seed + question_id`) so that
     * shuffling question 7's options does not depend on how many questions
     * came before it. The client reimplements this one; the questions
     * themselves it is handed pre-ordered.
     */
    public function test_option_shuffle_is_seeded_per_question(): void
    {
        $service = app(CbtExamService::class);

        foreach ($this->fixture['option_shuffle'] as $vector) {
            $actual = $service->seededShuffle(
                collect($vector['input']),
                $vector['attempt_seed'] + $vector['question_id']
            )->all();

            $this->assertSame(
                $vector['output'],
                $actual,
                sprintf('Option order drifted for attempt seed %d on question %d.', $vector['attempt_seed'], $vector['question_id'])
            );
        }
    }

    /**
     * The grouped case, which §10 singles out as the one most likely to drift:
     * group-level shuffle, optional within-group shuffle, and whole-group
     * subset draws, over a paper of two differently-sized passages and four
     * standalone objectives.
     *
     * Question and group ids are pinned to the fixture's values rather than
     * left to auto-increment, so a vector reads as a paper rather than as an
     * opaque list of numbers.
     */
    public function test_grouped_paper_composition_matches_the_committed_vectors(): void
    {
        $this->seedFixtureQuestions();
        $service = app(CbtExamService::class);

        foreach ($this->fixture['grouped_papers'] as $index => $vector) {
            $exam = $this->examFor($vector['exam']);
            $this->attachFixtureQuestions($exam);

            $actual = $service->composePaper($exam, $vector['seed']);

            $this->assertSame(
                $vector['question_order'],
                $actual,
                sprintf(
                    'Grouped paper vector %d drifted (seed %d, shuffle_questions=%s, shuffle_within_group=%s, questions_per_attempt=%s).',
                    $index,
                    $vector['seed'],
                    var_export((bool) $vector['exam']['shuffle_questions'], true),
                    var_export((bool) $vector['exam']['shuffle_within_group'], true),
                    var_export($vector['exam']['questions_per_attempt'], true)
                )
            );
        }
    }

    /**
     * Build the fixture's paper with its exact ids. Groups first, because the
     * questions carry foreign keys to them.
     */
    private function seedFixtureQuestions(): void
    {
        $groupIds = collect($this->fixture['attached_questions'])
            ->pluck('group_id')
            ->filter()
            ->unique();

        foreach ($groupIds as $groupId) {
            DB::table('cbt_question_groups')->insert([
                'id' => $groupId,
                'school_id' => $this->school->id,
                'subject_id' => $this->subject->id,
                'title' => "Passage {$groupId}",
                'stimulus' => 'Fixture stimulus.',
                'content_format' => 'plain',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        foreach ($this->fixture['attached_questions'] as $row) {
            DB::table('question_bank')->insert([
                'id' => $row['id'],
                'school_id' => $this->school->id,
                'subject_id' => $this->subject->id,
                'group_id' => $row['group_id'],
                'group_sequence' => $row['group_sequence'],
                'question' => "Fixture question {$row['id']}",
                'question_type' => 'multiple_choice',
                'options' => json_encode(['A' => 'one', 'B' => 'two']),
                'correct_answer' => 'A',
                'marks' => 1,
                'status' => 'approved',
                'content_format' => 'plain',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }

    private function examFor(array $settings): CbtExam
    {
        return CbtExam::create([
            'school_id' => $this->school->id,
            'subject_id' => $this->subject->id,
            'class_id' => $this->class->id,
            'title' => 'Parity paper',
            'duration_minutes' => 60,
            'status' => 'published',
            'opens_at' => now()->subMinute(),
            'closes_at' => now()->addHours(2),
            'shuffle_questions' => (bool) $settings['shuffle_questions'],
            'shuffle_within_group' => (bool) $settings['shuffle_within_group'],
            'shuffle_options' => false,
            'questions_per_attempt' => $settings['questions_per_attempt'],
            'max_attempts' => 1,
            'created_by' => $this->teacher->id,
        ]);
    }

    private function attachFixtureQuestions(CbtExam $exam): void
    {
        $index = 0;
        foreach ($this->fixture['attached_questions'] as $row) {
            CbtExamQuestion::create([
                'exam_id' => $exam->id,
                'question_id' => $row['id'],
                'order_index' => ++$index,
            ]);
        }
    }

    /**
     * The LCG constants themselves, asserted against the fixture's own
     * description of them. A client author reads this file to know what to
     * implement, so the numbers it quotes must be the numbers in use.
     */
    public function test_the_fixture_documents_the_algorithm_actually_in_use(): void
    {
        $this->assertSame(16807, $this->fixture['lcg']['multiplier']);
        $this->assertSame(2147483647, $this->fixture['lcg']['modulus']);

        // Reimplemented here from the fixture's prose, not called from the
        // service: this asserts the description is followable.
        $values = range(0, 9);
        $state = 4242 % 2147483647;
        if ($state <= 0) {
            $state += 2147483646;
        }
        for ($i = count($values) - 1; $i > 0; $i--) {
            $state = ($state * 16807) % 2147483647;
            $j = $state % ($i + 1);
            [$values[$i], $values[$j]] = [$values[$j], $values[$i]];
        }

        $this->assertSame(
            app(CbtExamService::class)->seededShuffle(collect(range(0, 9)), 4242)->all(),
            $values,
            'The algorithm described in the fixture no longer matches the one the server runs.'
        );
    }

    /**
     * Grouping is additive: a paper with no groups at all must order exactly
     * as it did before any of this existed. Every question in every bank today
     * has a null group_id, so this is the compatibility case, not an edge one.
     */
    public function test_an_ungrouped_paper_orders_as_a_flat_shuffle(): void
    {
        $exam = $this->examFor([
            'shuffle_questions' => true,
            'shuffle_within_group' => false,
            'questions_per_attempt' => null,
        ]);

        $ids = [];
        for ($i = 0; $i < 8; $i++) {
            $ids[] = QuestionBankItem::create([
                'school_id' => $this->school->id,
                'subject_id' => $this->subject->id,
                'question' => "Standalone {$i}",
                'question_type' => 'true_false',
                'correct_answer' => 'true',
                'marks' => 1,
                'status' => 'approved',
            ])->id;
        }

        $index = 0;
        foreach ($ids as $id) {
            CbtExamQuestion::create(['exam_id' => $exam->id, 'question_id' => $id, 'order_index' => ++$index]);
        }

        $service = app(CbtExamService::class);

        $this->assertSame(
            $service->seededShuffle(collect($ids), 4242)->all(),
            $service->composePaper($exam, 4242)
        );
    }
}
